name: coloring_api
description: "Coloring Api"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon: ^22.4.0



flutter:
  plugin:
    platforms:
      android:
        package: com.example.coloringapi.coloring_api
        pluginClass: ColoringApiPlugin
      ios:
        pluginClass: ColoringApiPlugin


