name: flutter_drawing_board
description: A Flutter package of drawing board, provides basic drawing tools, canvas operations, and image data acquisition.
version: 0.9.4
homepage: https://github.com/fluttercandies/flutter_drawing_board

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter